# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_MMIntAdd_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_MMIntAdd_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_MMIntAdd_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_MMIntAdd_rcpparma_bothproducts`, x)
}

elementwise_pow <- function(A, p) {
    .Call(`_MMIntAdd_elementwise_pow`, A, p)
}

TmatL <- function(Inspec, Timepoints) {
    .Call(`_MMIntAdd_TmatL`, Inspec, Timepoints)
}

TmatR <- function(Inspec, Timepoints) {
    .Call(`_MMIntAdd_TmatR`, Inspec, Timepoints)
}

TmatLR <- function(Inspec, Timepoints) {
    .Call(`_MMIntAdd_TmatLR`, Inspec, Timepoints)
}

Log_likelihood <- function(X, Delta, mimic, tL, tLR, tR, beta0, lambda0) {
    .Call(`_MMIntAdd_Log_likelihood`, X, Delta, mimic, tL, tLR, tR, beta0, lambda0)
}

Update_cpp_Zero <- function(X, Delta, Inspec, mimic, tL, tLR, tR, beta0, lambda0) {
    .Call(`_MMIntAdd_Update_cpp_Zero`, X, Delta, Inspec, mimic, tL, tLR, tR, beta0, lambda0)
}

Main_func_cpp <- function(X, Delta, Inspec, mimic, Max_iter, Tol) {
    .Call(`_MMIntAdd_Main_func_cpp`, X, Delta, Inspec, mimic, Max_iter, Tol)
}

Profile_Update_cpp <- function(X, Delta, Inspec, mimic, tL, tLR, tR, beta0, lambda0) {
    .Call(`_MMIntAdd_Profile_Update_cpp`, X, Delta, Inspec, mimic, tL, tLR, tR, beta0, lambda0)
}

Profile_Main_cpp <- function(beta0, lambda0, X, Delta, Inspec, mimic, Max_iter, Tol) {
    .Call(`_MMIntAdd_Profile_Main_cpp`, beta0, lambda0, X, Delta, Inspec, mimic, Max_iter, Tol)
}

SE_cal_cpp_one <- function(beta0, lambda0, lgvalue, X, Delta, Inspec, mimic, Max_iter, Tol, hn) {
    .Call(`_MMIntAdd_SE_cal_cpp_one`, beta0, lambda0, lgvalue, X, Delta, Inspec, mimic, Max_iter, Tol, hn)
}

SE_cal_cpp <- function(beta0, lambda0, lgvalue, X, Delta, Inspec, mimic, Max_iter, Tol, hn) {
    .Call(`_MMIntAdd_SE_cal_cpp`, beta0, lambda0, lgvalue, X, Delta, Inspec, mimic, Max_iter, Tol, hn)
}

SE_cal_cpp_gen <- function(beta0, lambda0, lgvalue, X, Delta, Inspec, mimic, Max_iter, Tol, hn) {
    .Call(`_MMIntAdd_SE_cal_cpp_gen`, beta0, lambda0, lgvalue, X, Delta, Inspec, mimic, Max_iter, Tol, hn)
}

Log_likelihood_test <- function(parameter, X, Delta, mimic, tL, tLR, tR) {
    .Call(`_MMIntAdd_Log_likelihood_test`, parameter, X, Delta, mimic, tL, tLR, tR)
}

Log_likelihood_Dep2 <- function(X, Delta, mimic, tL, tLR, tR, beta0, lambda0) {
    .Call(`_MMIntAdd_Log_likelihood_Dep2`, X, Delta, mimic, tL, tLR, tR, beta0, lambda0)
}

Update_cpp_Dep2 <- function(X, Delta, Inspec, mimic, tL, tLR, tR, beta0, lambda0) {
    .Call(`_MMIntAdd_Update_cpp_Dep2`, X, Delta, Inspec, mimic, tL, tLR, tR, beta0, lambda0)
}

Main_func_Dep <- function(X, Delta, Inspec, mimic, Max_iter, Tol) {
    .Call(`_MMIntAdd_Main_func_Dep`, X, Delta, Inspec, mimic, Max_iter, Tol)
}

Profile_Update_Dep2 <- function(X, Delta, Inspec, mimic, tL, tLR, tR, beta0, lambda0) {
    .Call(`_MMIntAdd_Profile_Update_Dep2`, X, Delta, Inspec, mimic, tL, tLR, tR, beta0, lambda0)
}

Profile_Main_Dep2 <- function(beta0, lambda0, X, Delta, Inspec, mimic, Max_iter, Tol) {
    .Call(`_MMIntAdd_Profile_Main_Dep2`, beta0, lambda0, X, Delta, Inspec, mimic, Max_iter, Tol)
}

SE_cal_Dep_one <- function(beta0, lambda0, lgvalue, X, Delta, Inspec, mimic, Max_iter, Tol, hn) {
    .Call(`_MMIntAdd_SE_cal_Dep_one`, beta0, lambda0, lgvalue, X, Delta, Inspec, mimic, Max_iter, Tol, hn)
}

